### ISSUE TITLE
Facebook megosztáshoz og meta tagok

### ISSUE THREAD

**Issue by borazslo** [molnarm/zsolozsma#2]
Ha facebookon megosztom a linket, akkor tök kevés infó megy át. Nem derül ki, hogy szentmise is, meg egy kép valami is jól jönne. 

A header-ben lehetne állandó meta tagokat tenni:
```
<meta property="og:url"                content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="When Great Minds Don’t Think Alike" />
<meta property="og:description"        content="How much does culture influence creative thinking?" />
<meta property="og:image"              content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />
```
Forrás: https://developers.facebook.com/docs/sharing/webmasters/

Ellenőrizni és frissíteni azt hogy a facebook mit lát, azt itt lehet: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fzsolozsma.herokuapp.com%2F

**Comment by molnarm** [comment]
Köszi, ez tök jó ötlet, délután ránézek.

**Comment by molnarm** [comment]
1d52814 Raktam minden oldalra, hogy látszódjon egy-egy helyszín vagy szertartás neve is, ha olyan oldalt oszt meg valaki.
![image](https://user-images.githubusercontent.com/517812/99258549-05b56700-2819-11eb-9ff6-b6654ae9816e.png)
