### ISSUE TITLE
Beágyazás / widget / reklám

### ISSUE THREAD

**Issue by borazslo** [molnarm/zsolozsma#27]
A miserend.hu honlapon jól lehetne reklámozni ezt az oldalt, hiszen sokaknak szüksége van online változatra.

- Legegyszerűbb: címlapra link, valami logóval. Elég uncsi.
- Inkább: címlapra valami widget félével (vagy API)-val betenni az aktuálisan pillanat élőinek sorát. Aztán megnyílni már a helyén nyílik meg.
- Sok macera: összekötni a kettőt, így az itteni adatbázisban szereplő templomok miserendes oldalán ott lenne az ikon, hogy online is közvetítés és itt és itt lehet elérni. 
- Még több macera: nem csupán a link jelenik meg a miserend.hu-s templom oldalán, hanem az szépen váltja a színét is az aktuális örömnek megfelelően.

**Comment by molnarm** [comment]
Valami API-félét összerakhatok, még akár azt is lehet, hogy a miserendes ID-kat is felveszem a helyszínekhez, de a többi részét a miserend.hu oldaláról kell majd megoldani.

**Comment by borazslo** [comment]
Persze a miserend.hu oldali teendő az én dologom.

**Comment by molnarm** [comment]
Most már működnek ezek:
https://zsolozsma.herokuapp.com/miserend/2725
https://zsolozsma.herokuapp.com/miserend/2725/?json
Részletek: https://github.com/molnarm/zsolozsma#api

Nem tudom, mekkor forgalma van a miserend.hu-nak, eddig elketyegett az alkalmazás a Heroku ingyenes szolgáltatásain, ha legalább azt cache-elnétek, hogy melyik templomhoz nincsenek közvetítések (404), az jó lenne ;-)

**Comment by borazslo** [comment]
Módosítási javaslataim:
- `state `helyett/melett egy `duration`: Az agresszív cache miatt a state sokszor nem releváns, hanem én találom ki a várható hossz alapján.
- `location_url `vagy valami hasonló: Hogy ki lehessen írni, hogy "További közvetítések a helyszínről ezen a linken érhetőek el." (Persze mintha ékezetmentesítés, aztán kisebetűsítés, aztán szünetek helyett kötőjelek, de akkor is egyszerűbb volna "tisztán" játszani.)

**Comment by borazslo** [comment]
![image](https://user-images.githubusercontent.com/2767787/108372981-abed8000-71ff-11eb-88e6-bdc2e92feaa0.png)

**Comment by molnarm** [comment]
Beraktam a `duration`t. A további közvetítések linkje egy templomnál ugyanaz, mint az API lekérdezés, csak `?json` nélkül.
