### ISSUE TITLE
Értesítő

### ISSUE THREAD

**Issue by borazslo** [molnarm/zsolozsma#4]
Van, hogy megnyitom az oldalt a böngészőben és kiválasztom, hogy az esti dicséretbe szeretnék bekapcsolódni. Aztán másutt böngészek és akár el is felejtem, hiszen rohan az idő. És akkor milyen jó lenne, ha felugrana a böngésző értesítő akármi, hogy eljött az idő, kezdődik. Természetesen opcionálisan. Akár csak egy valamire - amire a user kattint - akár amíg nyitva van, addig minden indulónál szól (abból lehet, túl sok lesz egy idő után).

**Comment by molnarm** [comment]
Már meg lehet nyitni előre is közvetítéses oldalt, a kezdéskor magától frissül.
A támogatott böngészőkben lehet értesítést kérni, ami 1 perccel a közvetítés indulása előtt és a kezdéskor jelenik meg. Csak akkor működik, ha nyitva marad az oldal.
